### ISSUE TITLE
which diff format to support?

### ISSUE THREAD

**Issue by hannesm** [hannesm/patch#2]
the overall question is: what is the input for this library? it seems like the term "unified diff" is not well-defined, and "extensible". the pragmatic solution is "whatever opam gives us".

opam itself uses [`gpatch -p1 -i p'`](https://github.com/ocaml/opam/blob/2.0.4/src/core/opamSystem.ml#L1253) to apply the patch (which has been processed by [`translate_patch`](https://github.com/ocaml/opam/blob/2.0.4/src/core/opamSystem.ml#L927-L1233) (something with CR/LF, but unsure about the concrete semantics).

generating the diffs (for the repositories I mostly care about):
- [HTTP](https://github.com/ocaml/opam/blob/2.0.4/src/repository/opamRepositoryBackend.ml#L88-L94) uses the repository backend, calling out to `diff -ruaN` (recursive, unified, `-a` is "treat all files as text", `-N` is "new file": if a file found in new which doesn't exist in old, treat old as empty)
- [git](https://github.com/ocaml/opam/blob/2.0.4/src/repository/opamGit.ml#L152-L170) uses  `git repo_root ~stdout:patch_file [ "-c" ; "diff.noprefix=false" ; "diff" ; "--no-ext-diff" ; "-R" ; "-p" ; rref; "--" ]` (which means: `-c` is "combined", `no-ext-diff` to use builtin one, `-R` swap args (new/old), `-p` "something to use with patch, a unified diff", `diff.noprefix=false` ensure a `-p1` is generated)

**Comment by hannesm** [comment]
now, from https://www.artima.com/weblogs/viewpost.jsp?thread=164293 about the "specification of diff":
I haven't found a satisfactory specification of the unified diff format (the one on the GNU website is hopelessly incomplete). Here's what I've discovered by experimenting with diff(1) on Red Hat Linux; this identifies itself as 'diff (GNU diffutils) 2.8.1'. Hopefully this is useful for someone who needs to generate unified diffs or who needs to parse them. (I had both needs recently. :-)

The header lines look like this:

`indicator ' ' filename '\t' date ' ' time ' ' timezone`

where:

- indicator is '---' for the old file and '+++' for the new
- date has the form YYYY-MM-DD
- time has the form hh:mm:ss.nnnnnnnnn on a 24-hour clock
- timezone is has the form ('+'|'-') hhmm where hhmm is hours and minutes east (if the sign is +) or west (if the sign is -) of GMT/UTC

Each chunk starts with a line that looks like this:

`'@@ -' range ' +' range ' @@'`

where range is either one unsigned decimal number or two separated by a comma. The first number is the start line of the chunk in the old or new file. The second number is chunk size in that file; it and the comma are omitted if the chunk size is 1. (Email from a reader suggests that this omission is optional and may be phased out.) If the chunk size is 0, the first number is one lower than one would expect (it is the line number after which the chunk should be inserted or deleted; in all other cases it gives the first line number or the replaced range of lines).

A chunk then continues with lines starting with ' ' (common line), '-' (only in old file), or '+' (only in new file). If the last line of a file doesn't end in a newline character, it is displayed with a newline character, and the following line in the chunk has the literal text (starting in the first column):

`\ No newline at end of file`

**Comment by hannesm** [comment]
from https://git-scm.com/docs/git-diff#_combined_diff_format:
combined diff format

Any diff-generating command can take the -c or --cc option to produce a combined diff when showing a merge. This is the default format when showing merges with git-diff[1] or git-show[1]. Note also that you can give the -m option to any of these commands to force generation of diffs with individual parents of a merge.

A combined diff format looks like this:

```
diff --combined describe.c
index fabadb8,cc95eb0..4866510
--- a/describe.c
+++ b/describe.c
@@@ -98,20 -98,12 +98,20 @@@
	return (a_date > b_date) ? -1 : (a_date == b_date) ? 0 : 1;
  }

- static void describe(char *arg)
 -static void describe(struct commit *cmit, int last_one)
++static void describe(char *arg, int last_one)
  {
 +	unsigned char sha1[20];
 +	struct commit *cmit;
	struct commit_list *list;
	static int initialized = 0;
	struct commit_name *n;

 +	if (get_sha1(arg, sha1) < 0)
 +		usage(describe_usage);
 +	cmit = lookup_commit_reference(sha1);
 +	if (!cmit)
 +		usage(describe_usage);
 +
	if (!initialized) {
		initialized = 1;
		for_each_ref(get_name);
```

It is preceded with a "git diff" header, that looks like this (when -c option is used):

`diff --combined file`

or like this (when --cc option is used):

`diff --cc file`

It is followed by one or more extended header lines (this example shows a merge with two parents):

```
index <hash>,<hash>..<hash>
mode <mode>,<mode>..<mode>
new file mode <mode>
deleted file mode <mode>,<mode>
```

The `mode <mode>,<mode>..<mode>` line appears only if at least one of the `<mode>` is different from the rest. Extended headers with information about detected contents movement (renames and copying detection) are designed to work with diff of two `<tree-ish>` and are not used by combined diff format.

It is followed by two-line from-file/to-file header

```
--- a/file
+++ b/file
```

Similar to two-line header for traditional unified diff format, /dev/null is used to signal created or deleted files.

Chunk header format is modified to prevent people from accidentally feeding it to patch -p1. Combined diff format was created for review of merge commit changes, and was not meant for apply. The change is similar to the change in the extended index header:

```
@@@ <from-file-range> <from-file-range> <to-file-range> @@@
```

There are (number of parents + 1) `@` characters in the chunk header for combined diff format.

Unlike the traditional unified diff format, which shows two files A and B with a single column that has `-` (minus  -  appears in A but removed in B), `+` (plus  -  missing in A but added to B), or ` ` (space  - unchanged) prefix, this format compares two or more files file1, file2,…​ with one file X, and shows how X differs from each of fileN. One column for each of fileN is prepended to the output line to note how X’s line is different from it.

A - character in the column N means that the line appears in fileN but it does not appear in the result. A + character in the column N means that the line appears in the result, and fileN does not have that line (in other words, the line was added, from the point of view of that parent).

In the above example output, the function signature was changed from both files (hence two - removals from both file1 and file2, plus ++ to mean one line that was added does not appear in either file1 or file2). Also eight other lines are the same from file1 but do not appear in file2 (hence prefixed with +).

When shown by git diff-tree -c, it compares the parents of a merge commit with the merge result (i.e. file1..fileN are the parents). When shown by git diff-files -c, it compares the two unresolved merge parents with the working tree file (i.e. file1 is stage 2 aka "our version", file2 is stage 3 aka "their version").

**Comment by hannesm** [comment]
i suspect the latter format, with the additional constraint of only two `@@` (i.e. no n-way merge) is necessary as a first step

**Comment by hannesm** [comment]
from the git documentation, this may be useful as well (from https://git-scm.com/docs/git-diff#_generating_patches_with_p):

Generating patches with -p

When "git-diff-index", "git-diff-tree", or "git-diff-files" are run with a -p option, "git diff" without the --raw option, or "git log" with the "-p" option, they do not produce the output described above; instead they produce a patch file. You can customize the creation of such patches via the GIT_EXTERNAL_DIFF and the GIT_DIFF_OPTS environment variables.

What the -p option produces is slightly different from the traditional diff format:

- It is preceded with a "git diff" header that looks like this:

`diff --git a/file1 b/file2`

- The a/ and b/ filenames are the same unless rename/copy is involved. Especially, even for a creation or a deletion, /dev/null is not used in place of the a/ or b/ filenames.

- When rename/copy is involved, file1 and file2 show the name of the source file of the rename/copy and the name of the file that rename/copy produces, respectively.

- It is followed by one or more extended header lines:

```
old mode <mode>
new mode <mode>
deleted file mode <mode>
new file mode <mode>
copy from <path>
copy to <path>
rename from <path>
rename to <path>
similarity index <number>
dissimilarity index <number>
index <hash>..<hash> <mode>
```

- File modes are printed as 6-digit octal numbers including the file type and file permission bits.

- Path names in extended headers do not include the a/ and b/ prefixes.

- The similarity index is the percentage of unchanged lines, and the dissimilarity index is the percentage of changed lines. It is a rounded down integer, followed by a percent sign. The similarity index value of 100% is thus reserved for two equal files, while 100% dissimilarity means that no line from the old file made it into the new one.

- The index line includes the SHA-1 checksum before and after the change. The <mode> is included if the file mode does not change; otherwise, separate lines indicate the old and the new mode.

- Pathnames with "unusual" characters are quoted as explained for the configuration variable core.quotePath (see git-config[1]).

- All the file1 files in the output refer to files before the commit, and all the file2 files refer to files after the commit. It is incorrect to apply each change to each file sequentially. For example, this patch will swap a and b:

```
diff --git a/a b/b
rename from a
rename to b
diff --git a/b b/a
rename from b
rename to a
```

**Comment by AltGr** [comment]
>  the pragmatic solution is "whatever opam gives us".

and what opam cares about is basically "whatever git gives us" :)
So I believe your last comment is the most relevant here. We can otherwise adjust our `diff` output as needed. Or another option could even be to use `git`'s `--ext-diff` option to generate custom output, but having to rely on an external binary could be annoying.

Thanks for all the research; your remark on swapping files is particularly interesting :)

**Comment by hannesm** [comment]
@AltGr you mean (from git help diff) -- yes, I was surprised by that:
```
       -R
           Swap two inputs; that is, show differences from index or on-disk
           file to tree contents.
```

**Comment by hannesm** [comment]
I took decisions and fixed some issues based on what I got from `opam` in #4, closing this. Feel free to open specific issues if some diff feature (or dialect) is not present but desired. I also opened the scope of `patch` to cope with (a) unified diffs from `diff -u` (b) git diff from `git show / git diff -p`.
